In [ ]:
#python assignment 20

#Q1 Set the variable test1 to the string &#39;This is a test of the emergency text system,&#39; and save test1 to a file named test.txt.

test1 = 'This is a test of the emergency text system,'

with open('test.txt', 'w') as file:
    file.write(test1)
#In this code, we assign the string 'This is a test of the emergency text system,' to the variable test1. Then, we open a file named test.txt in write mode ('w'), using the open() function. We use a with statement to automatically handle the closing of the file.

In [ ]:
#Q2  Read the contents of the file test.txt into the variable test2. Is there a difference between test 1 and test 2?
#with open('test.txt', 'r') as file:
    test2 = file.read()

# Comparing test1 and test2
if test1 == test2:
    print("There is no difference between test1 and test2.")
else:
    print("There is a difference between test1 and test2.")
In this code, we open the file test.txt in read mode ('r') using the open() function and read its contents using the read() method of the file object. The content is then stored in the variable test2.

In [5]:
#Q3 Create a CSV file called books.csv by using these lines:
#title,author,year
#The Weirdstone of Brisingamen,Alan Garner,1960
#Perdido Street Station,China Miéville,2000
#Thud!,Terry Pratchett,2005
#The Spellman Files,Lisa Lutz,2007
#Small Gods,Terry Pratchett,1992
import csv

data = [
    ['title', 'author', 'year'],
    ['The Weirdstone of Brisingamen', 'Alan Garner', '1960'],
    ['Perdido Street Station', 'China Miéville', '2000'],
    ['Thud!', 'Terry Pratchett', '2005'],
    ['The Spellman Files', 'Lisa Lutz', '2007'],
    ['Small Gods', 'Terry Pratchett', '1992']
]

with open('books.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerows(data)

In [8]:
#Q4 Use the sqlite3 module to create a SQLite database called books.db, and a table called books with
#these fields: title (text), author (text), and year (integer).
import sqlite3

# Create a connection to the database
conn = sqlite3.connect('books.db')

# Create a cursor object to execute SQL statements
cursor = conn.cursor()

# Create the books table
cursor.execute('''
    CREATE TABLE books (
        title TEXT,
        author TEXT,
        year INTEGER
    )
''')

# Commit the changes and close the connection
conn.commit()
conn.close()

In [9]:
#Q5 Read books.csv and insert its data into the book table.
import csv
import sqlite3

# Open the CSV file for reading
with open('books.csv', 'r') as file:
    # Create a CSV reader object
    reader = csv.reader(file)
    
    # Create a connection to the database
    conn = sqlite3.connect('books.db')
    cursor = conn.cursor()
    
    # Iterate over the rows in the CSV file
    for row in reader:
        # Insert each row into the books table
        cursor.execute('INSERT INTO books (title, author, year) VALUES (?, ?, ?)', row)
    
    # Commit the changes and close the connection
    conn.commit()
    conn.close()

In [ ]:
#Q6 Select and print the title column from the book table in alphabetical order.
import sqlite3

# Create a connection to the database
conn = sqlite3.connect('books.db')
cursor = conn.cursor()

# Select the title column from the books table in alphabetical order
cursor.execute('SELECT title FROM books ORDER BY title ASC')

# Fetch all the rows returned by the query
rows = cursor.fetchall()

# Print the titles
for row in rows:
    print(row[0])

# Close the connection
conn.close()

In [ ]:
#Q7 From the book table, select and print all columns in the order of publication.
import sqlite3

# Create a connection to the database
conn = sqlite3.connect('books.db')
cursor = conn.cursor()

# Select all columns from the books table in the order of publication
cursor.execute('SELECT * FROM books ORDER BY year ASC')

# Fetch all the rows returned by the query
rows = cursor.fetchall()

# Print the columns
for row in rows:
    print(row)

# Close the connection
conn.close()

In [ ]:
#Q8 Use the sqlalchemy module to connect to the sqlite3 database books.db that you just made in
#exercise 6.
from sqlalchemy import create_engine

# Create a SQLAlchemy engine to connect to the database
engine = create_engine('sqlite:///books.db')

# Connect to the database
conn = engine.connect()

# Perform database operations...

# Close the connection
conn.close()

In [ ]:
#Q10. Increment the count field of test and print it.
import redis

#Connect to the Redis server
r = redis.Redis(host='localhost', port=6379, db=0)

#Increment the 'count' field of 'test'
r.hincrby('test', 'count', 1)

#Get the updated value of the 'count' field
count_value = r.hget('test', 'count')

#Print the updated count value
print(count_value)

#Close the Redis connection
r.close()